name: spine_core
description: The spine-core runtime provides functionality to load and manipulate Spine skeletal animation data using Dart.
version: 0.2.0
homepage: https://github.com/jtakakura/spine_core/
author: Junji Takakura <j.takakura@gmail.com>

environment:
  sdk: ">=2.8.0 <3.0.0"


dev_dependencies:
  test: ^1.0.0
